### ISSUE TITLE
Kubernetes version specification in main.tf conflict

### ISSUE THREAD

**Issue by cslocum** [pangeo-data/terraform-deploy#17]
This change was required while trying to run `terraform init`.  Unfortunately I do not have the error that required this.  I will try to dig it up.

```
(base) [ec2-user@ip-172-31-94-72 cloud-infrastructure]$ git diff aws/main.tf
diff --git a/aws/main.tf b/aws/main.tf
index 2021b38..fd72737 100644
--- a/aws/main.tf
+++ b/aws/main.tf
@@ -24,7 +24,6 @@ provider "kubernetes" {
   cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
   token                  = data.aws_eks_cluster_auth.cluster.token
   load_config_file       = false
-  version                = "~> 1.10.0"
 }
```

**Comment by salvis2** [comment]
@cslocum , I know there are some features past v1.10.0 that are nice. We had the version pinned there because there was a breaking bug with v1.11.0, see [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/733). They have fixed that, so if you specify `version = "~>1.11.1"`, it wouldn't be a problem. 

Does that version allow you to run `terraform init`?
